config/routes.rb
RoboApp::Application.routes.draw do

  devise_for :users

  resource :robot
  resources :transactions

  root to: 'robots#show'

end

app/models/robot.rb
require 'open-uri'
class Robot 


	
	# @@url = 'http://192.168.0.44:1235/'
	@@url = 'http://127.0.0.1:4567/'
	@@api_key = '4'

	def self.run_command(cmd)
		if [:forward, :backward, :slow_forward, :slow_backward, :left, :right, :run, :attack].include?(cmd)
			Robot.send cmd
		end

	end

	def self.lock
		open(@@url + @@api_key + '/lock').read 
	end

	def self.proximity
		open(@@url + '/proximity').read
		
	end

	def self.forward
		open(@@url + @@api_key + '/forward').read
	end

	def self.backward
		open(@@url + @@api_key + '/backward').read
	end

	def self.slow_forward
		open(@@url + @@api_key + '/slow_forward').read
	end

	def self.slow_backward
		open(@@url + @@api_key + '/slow_backward').read
	end

	def self.left
		open(@@url + @@api_key + '/left').read
	end

	def self.right
		open(@@url + @@api_key + '/right').read
	end

	def self.run
		open(@@url + @@api_key + '/run').read
	end

	def self.attack
		open(@@url + @@api_key + '/attack').read
	end
end

app/models/spending.rb
class Spending < ActiveRecord::Base
	belongs_to :user
	belongs_to :transaction
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	attr_accessor :first_name, :last_name, :number, :month, :year, :verification_value
	validates :amount, presence: true, numericality: true
	validates :first_name, :last_name, :number, :month, :year, :verification_value, presence: true
	validate :credit_card_valid
	belongs_to :user, counter_cache: true
	has_many :spendings

	before_create :purchase

	def credit_card_valid
		errors.add(:base, "Credit card is invalid") unless credit_card.valid?	
	end

	def credit_card
			ActiveMerchant::Billing::CreditCard.new(
										:first_name         => first_name,
		                :last_name          => last_name,
		                :number             => number,
		                :month              => month,
		                :year               => year,
		                :verification_value => verification_value)	
	end

	def purchase
		@price = amount*100
		response = TransactionGateway.get.purchase(@price, credit_card)
		if response.success?
		UserMailer.transaction_mail(self.user.email).deliver
		return true
		else
			errors.add(:base, "Transaction rejected : #{response.message}")
			return false
		end

end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :transactions
  has_many :spendings


  def payment
    self.credits -= 1 
    save
  end

  def has_credits?
    self.credits > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  rescue_from ::Errno::ECONNREFUSED, :with => :server_not_found

  protect_from_forgery with: :exception

 private

  def server_not_found
  	render 'error'
  end
  	
  
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  
  before_filter :authenticate_user!
  before_action :try_to_lock,  only: [ :update ] 
  rescue_from SystemCallError, :with => :server_not_found

def update

 
      if current_user.has_credits?
        if params[:cmd]
          params[:cmd].split(" ").each do |command|
          Robot.run_command(command.to_sym)
          end
        else
          Robot.run_command(params[:cmd])
        end
          current_user.payment
      else
          flash[:notice] = 'Buy more credits!'
        
      end
  redirect_to :back

#   if params[:cmd]
#         params[:cmd].split(" ").each do |command|
#           Robot.run_command(command.to_sym)
#         end
#   else
#         Robot.run_command(params[:cmd])
#   end
#   redirect_to :back
 end

def show 
  @proximity = Robot.proximity 
end


  private

  def try_to_lock 
    if Robot.lock
    else
      flash[:notice] = 'Try again in a few seconds'
    end
  end

  def server_not_found
    render 'error'
  end
    
  

end
 

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	before_filter :authenticate_user!

	def new
		@transaction = Transaction.new
	end

	def create
		@transaction = current_user.transactions.build(transaction_params)
		@transaction.credits = @transaction.amount
		current_user.credits += @transaction.credits
		if current_user.save
			# current_user.credits += @transaction.credits
			redirect_to root_path
		else
			flash[:notice] = "Please fill in all fields"
			render 'new'
		end
	end

	private

	def transaction_params
		params.require(:transaction).permit(:first_name, :last_name, :number, :month, :year, :verification_value, :amount)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def robot_control_button(text, cmd)
		button_to text, {:controller => "robots", :action => "update", :cmd => cmd}, method: :put 
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Codystar|Monofett|Electrolize|Iceland&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <title>RoboApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- <div class="message">
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</div>
 -->
 <p class="navbar">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

 <% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/robots/error.html.erb
<div class='main_image'>
	<%=image_tag 'robot.png'%>
</div>

<h1 class="error">Server Problem Robot Sad :(</h1>

app/views/robots/index.html.erb
<%= button_to 'Right', robots_right_path %>
<%= button_to 'Left', robots_left_path %>
<%= button_to 'Forward', robots_forward_path %>
<%= button_to 'Backward', robots_backward_path %>
<%= button_to 'Slow Backward', robots_slow_backward_path %>
<%= button_to 'Slow Forward', robots_slow_forward_path %>
<%= button_to 'Run', robots_run_path %>
<%= button_to 'Attack', robots_attack_path %>
<%= button_to 'Proximity', robots_proximity_path method: :put%>

app/views/robots/show.html.erb
<header>
	<h1>Robo App</h1>
</header>

<div class='main_image'>
	<%=image_tag 'robot.png'%>
</div>
<div class='buttons main_buttons'>
	<div class='button left'><%= robot_control_button "Left", "left" %></div>
	<div class='button forward'><%= robot_control_button "Forward", "forward" %></div>
	<div class='button backward'><%= robot_control_button "Backward", "backward" %></div>
	<div class='button right'> <%= robot_control_button "Right", "right" %></div>
</div>
<div class='buttons secondary_buttons'>
	<div class='button slow_back'><%= robot_control_button "Slow Backward", "slow_backward" %></div>
	<div class='button slow_forw'><%= robot_control_button "Slow Forward", "slow_forward" %></div>
</div>
<div class='buttons third_buttons'>
	<div class='button run'><%= robot_control_button "Run", "run" %></div>
	<div class='button attack'><%= robot_control_button "Attack", "attack" %></div>
</div>
<div class="command_form">
<p><%= form_tag(robot_path, method: :put) do %>
  <%= text_area_tag :cmd, params[:cmd] %>
  <%= submit_tag("Send") %>
<% end %></p>

<div class='proximity'>
	Proximity:<%=@proximity%>
</div>

app/views/transactions/new.html.erb
<div id="form-main-window">
	<div class="form-header">
		<p>1 credit = 1 USD</p>
		<p>1 credit = super duper fun with amazing Robo for 60 seconds!!!!</p>

	</div>


	<%= form_for @transaction do |f|%>

	<div class='field'>
		<%= f.label :first_name %><br />
	 	<%= f.text_field :first_name, value: current_user.first_name %>
	</div>

	<div class='field'>	
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, value: current_user.last_name%>
	</div>

	<div class='field'>
		<%= f.label :amount %><br />
		<%= f.text_field :amount %>
	</div>

	<div class='field'>
		<%= f.label :number %><br />
		<%= f.text_field :number%>
	</div>

	<div class='field'>
		<%= f.label :month %><br />
		<%= f.text_field :month%>
	</div>

	<div class='field'>
		<%= f.label :year %><br />
		<%= f.text_field :year %>
	</div>

	<div class='field'>
		<%= f.label :verification_value %><br />
		<%= f.text_field :verification_value %></br>
	</div>

	<div class="actions"><%= f.submit "Send" %></div>
	<%end%>

</div>